---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: steves-app
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30005
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: steves-app
    spec:
      containers:
        - name: steves-container
          image: ssmackey/testing:latest
          ports:
            - containerPort: 8080
